### ISSUE TITLE
Make developer release with new packaging method

### ISSUE THREAD

**Issue by h-vn** [radiator-software/p5-net-ssleay#13]
PR #12 by @mohawk2 switched packaging to use ExtUtils-MakeMaker in addition to fixing build when paths had space characters. Make a CPAN developer release to get these changes tested.

**Comment by h-vn** [comment]
Merged, but need to update Changes in the next release to more clearly credit @mohawk2 for the work.

**Comment by mohawk2** [comment]
I am not very concerned with such credit, but I have much respect for your attention to that :-)
