### ISSUE TITLE
ASN1_TIME_timet returns incorrect timestamps

### ISSUE THREAD

**Issue by redneb** [radiator-software/p5-net-ssleay#148]
To reproduce, save the following as `cert.pem`:

    -----BEGIN CERTIFICATE-----
    MIIBPDCB76ADAgECAhQWTJm8Uf2q9/4IUTkvgQILkbZrpjAFBgMrZXAwFDESMBAG
    A1UEAwwJbG9jYWxob3N0MB4XDTE5MDgyOTEzNTA0OVoXDTE5MDgzMDEzNTA0OVow
    FDESMBAGA1UEAwwJbG9jYWxob3N0MCowBQYDK2VwAyEAAUhOvnRI+41nGm5xwcC3
    1hwtYw8zRjt8Tgm5a22DivCjUzBRMB0GA1UdDgQWBBTQEw8aqbVzQSfpm3tix1Fa
    RABOuzAfBgNVHSMEGDAWgBTQEw8aqbVzQSfpm3tix1FaRABOuzAPBgNVHRMBAf8E
    BTADAQH/MAUGAytlcANBAAWzNpTYHoES83+UvjDambfEHxRWhf8kvlD+Iper6LZg
    J6yXuzN9Otzrlzxngi5p1eSrknKy8XfM2C+sNkBGFwc=
    -----END CERTIFICATE-----

(note: it's an ED25519 certificate so it requires OpenSSL-1.1.1+, I used that algorithm to make the certificate short, the signature algorithm is irrelevant to the bug).

You can now ask `openssl` to report the expiration time of the about certificate:

    $ openssl x509 -in cert.pem -noout -enddate
    notAfter=Aug 30 13:50:49 2019 GMT

Let's try to do the same thing using `Net::SSLeay`. Create the following script (`test.pl`):

    use Net::SSLeay;
    
    my $bio = Net::SSLeay::BIO_new_file('cert.pem', 'r') or
    	die "Cannot read file: $!";
    my $cert = Net::SSLeay::PEM_read_bio_X509($bio);
    Net::SSLeay::BIO_free($bio);
    $cert or die 'Cannot parse X509 cert';
    my $t=Net::SSLeay::ASN1_TIME_timet(Net::SSLeay::X509_get_notAfter($cert));
    print $t,' => ',scalar(gmtime($t)),"\n";
    Net::SSLeay::X509_free($cert);

and test it (I am explicitly setting the `TZ` environment variable to make the script independent of the system's timezone settings):

    $ TZ=America/New_York ./test.pl
    1567194649 => Fri Aug 30 19:50:49 2019
    
    $ TZ=America/Chicago ./test.pl
    1567198249 => Fri Aug 30 20:50:49 2019

As you can see, the unix time that we get (`1567194649` vs `1567198249`) depends on the selected timezone (it shouldn't). Also, the expanded timestamp printed afterwards is supposed to be a UTC timestamp, so it should have been the same in both invocations of the script and equal to `Aug 30 13:50:49 2019`.

After some debugging, I tracked the problem down to the `ASN1_TIME_timet` function. In that function, the ASN1 time is parsed into a `struct tm` and then the `C` standard function `mktime` is used to convert that into a `time_t` value. The problem is that `mktime` expects that its argument is expressed in the local timezone of the system, whereas the ASN1 time is expressed in some (possibly) other timezone (typically UTC).

**Comment by h-vn** [comment]
I did some experimenting with this, and it seems that with OpenSSL 1.0.2 an easy possibility to get a UTC time stamp with ASN1_TIME_diff(). This can be done with 'from' time set to the fixed Jan 1 1970 epoch time. https://www.openssl.org/docs/manmaster/man3/ASN1_TIME_diff.html

With LibreSSL and earlier OpenSSL's more work seems to be needed.

Before anything gets changed, I'd like to understand better how to proceed. It looks like ASN1_TIME_timet() is not documented in SSLeay.pod and it's only use in in SSLeay.xs is OSCP_response_result(). I'll ping Steffen, who authored the OCSP support, about his views changing ASN1_TIME_timet(). Also, are you using the function directly, and thus could switch to something like ASN1_TIME_timet_gm() which would also return a UTC based time_t? Or did you notice this from OCSP timestamps?

**Comment by redneb** [comment]
In my actual code I am using `CERT_asHash` from `IO::Socket::SSL::Utils`. The reason that I reported the bug here instead of `IO::Socket::SSL::Utils` is because it is clear that this is bug in `ASN1_TIME_timet`. Note that there is no such thing as a UTC based or a non UTC based `time_t` (unix time); there is only one unix time and it has the same meaning everywhere. That's why I think the right course of action here is to fix `ASN1_TIME_timet` instead of introducing a new function.

**Comment by h-vn** [comment]
Regarding `time_t,` should we aim for not using it at all in this context? ASN1 time strings can go from year 0000 to year 9999 which is problematic with unsigned 32bit `time_t` definitions. I'm especially thinking calls that return time_t and are not part of OpenSSL API.

**Comment by miiichael** [comment]
So either `ASN1_TIME_timet()` needs to either be fixed, or go away altogether (forcing users such as IO::Socket::SSL to somehow convert timestamps some other way)?

Personally I don't think it's too much of an issue that (32 bit) time_t has a smaller range than the ASN1 type. 64 bit time_t will fix that, right? :P

**Comment by h-vn** [comment]
Closed by GH-248. Thanks Steffen!
