### ISSUE TITLE
Net::SSLeay::P_X509_REQ_add_extensions works only with DNS and URI

### ISSUE THREAD

**Issue by s482dcaw** [radiator-software/p5-net-ssleay#149]
The function Net::SSLeay::P_X509_REQ_add_extensions works only with DNS and URI type entries. The rest (RID,  OTHERNAME, EMAIL, X400, DIRNAME and didn't try IPADDR) are ignored

**Comment by s482dcaw** [comment]
Some more info:

O/S: openSuse Leap 15.1 JeOS
openssl-1.1.0i-lp151.1.1

I tried with the NetSSLeay that comes with the distribution (perl-Net-SSLeay-1.81-lp151.2.4) and I also tried downloading master from github and compiling. Both have the same result.

**Comment by h-vn** [comment]
Please see t/local/33_x509_create_cert.t. I changed the call to Net::SSLeay::P_X509_REQ_add_extensions to add altnames like this:
`Net::SSLeay::NID_subject_alt_name => 'DNS:s1.com,DNS:s2.com,email:foo@example.com,RID:1.2.3.4,otherName:2.3.4.5;UTF8:some other identifier,IP:10.20.30.41,IP:20.30.40.51',`

I then printed out the request ($req_pem) and the newly create certificate ($crt_pem) and pasted them to `openssl req -noout -text` and  `openssl x509 -noout -text`. Both the request and certificate had similar subjectAltName:

```
            X509v3 Subject Alternative Name: 
                DNS:s1.com, DNS:s2.com, email:foo@example.com, Registered ID:1.2.3.4, othername:<unsupported>, IP Address:10.20.30.41, IP Address:20.30.40.51

            X509v3 Subject Alternative Name: 
                DNS:s1.com, DNS:s2.com, email:foo@example.com, Registered ID:1.2.3.4, othername:<unsupported>, IP Address:10.20.30.41, IP Address:20.30.40.51
```

This worked the same with OpenSSL 0.9.8zh and 1.1.1e. I did not try with X400 or DIRNAME but at least RID, OTHERNAME, EMAIL and IPADDR looked good.

However, theres one thing I noticed: Net::SSLeay::X509_get_subjectAltNames() doesn't seem to understand X400, DIRNAME, nor EDIPARTY. If those are present, they are skipped and not returned. This contradicts what Pod manual says.

I'll see about updating the test to add more altnames.

Meanwhile, do you have a code snippet or more information that demonstrates the problem you saw?

**Comment by h-vn** [comment]
To correct my previous comment: Net::SSLeay::X509_get_subjectAltNames() but it does not understand RID, also known as registeredID. Pull request GH-149 adds support for registeredID up to 2500 characters long. It also enhances tests to add all supported subjectAltNames to certification request and then checks that they all were correctly copied to the signed certificate.

Please take a look at the changes, especially the updated tests, and tell if you still think there's  a problem with Net::SSLeay::P_X509_REQ_add_extensions().

**Comment by h-vn** [comment]
Changes merged with PR GH-167 now extend test that calls `Net::SSLeay::P_X509_REQ_add_extensions()`. The function is now called with DNS, URI and other name types and a new test checks that these names in request are successfully copied to the signed certificate.

No changes were done to `Net::SSLeay::P_X509_REQ_add_extensions()` but if there are still problems with the call, please create a new issue with a code example, if possible.
