### ISSUE TITLE
Failed t/local/10_rand.t

### ISSUE THREAD

**Issue by mche** [radiator-software/p5-net-ssleay#152]
Hi!

```
t/local/10_rand.t ...................... 1/52 
#   Failed test 'RAND_file_name returns defined value'
#   at t/local/10_rand.t line 18.
#          got: undef
#     expected: anything else
Use of uninitialized value $file_name in concatenation (.) or string at t/local/10_rand.t line 19.
# Looks like you failed 1 test of 52.
t/local/10_rand.t ...................... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/52 subtests 

```
full log [here](http://pastebin.calculate-linux.ru/ru/show/128183)

---

[@chrisnovakovic edit to add the full log from the link above, in case it goes missing:]

```
t/handle/local/05_use.t ................ ok   
t/local/01_pod.t ....................... skipped: Test::Pod 1.00 required for testing POD
t/local/02_pod_coverage.t .............. skipped: these tests are for only for release candidate testing. Enable with RELEASE_TESTING=1
t/local/03_use.t ....................... 1/1 # 
# Testing Net::SSLeay 1.88
# 
# Perl information:
#   Version:         '5.026001'
#   Executable path: '/home/guest/perl5/perlbrew/perls/perl-5.26.1/bin/perl'
# 
# libssl information:
#   SSLEAY_VERSION:      'OpenSSL 1.1.1d  10 Sep 2019'
#   SSLEAY_CFLAGS:       'compiler: x86_64-pc-linux-gnu-gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -march=native -O2 -pipe -fno-strict-aliasing -Wa,--noexecstack -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DZLIB -DNDEBUG  -DOPENSSL_NO_BUF_FREELISTS'
#   SSLEAY_BUILT_ON:     'built on: Thu Oct 17 13:30:14 2019 UTC'
#   SSLEAY_PLATFORM:     'platform: linux-x86_64'
#   SSLEAY_DIR:          'OPENSSLDIR: "/etc/ssl"'
#   OPENSSL_ENGINES_DIR: 'ENGINESDIR: "/usr/lib64/engines-1.1"'
t/local/03_use.t ....................... ok   
t/local/04_basic.t ..................... ok     
t/local/05_passwd_cb.t ................. ok     
t/local/06_tcpecho.t ................... ok   
t/local/07_sslecho.t ................... ok       
t/local/08_pipe.t ...................... ok     
t/local/09_ctx_new.t ................... ok     
t/local/10_rand.t ...................... 1/52 
#   Failed test 'RAND_file_name returns defined value'
#   at t/local/10_rand.t line 18.
#          got: undef
#     expected: anything else
Use of uninitialized value $file_name in concatenation (.) or string at t/local/10_rand.t line 19.
# Looks like you failed 1 test of 52.
t/local/10_rand.t ...................... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/52 subtests 
t/local/11_read.t ...................... ok     
t/local/15_bio.t ....................... ok   
t/local/20_autoload.t .................. ok       
t/local/21_constants.t ................. ok       
t/local/30_error.t ..................... ok     
t/local/31_rsa_generate_key.t .......... ok     
t/local/32_x509_get_cert_info.t ........ ok         
t/local/33_x509_create_cert.t .......... ok       
t/local/34_x509_crl.t .................. ok     
t/local/35_ephemeral.t ................. skipped: libressl and OpenSSL 1.1 removed support for ephemeral/temporary RSA private keys
t/local/36_verify.t .................... ok       
t/local/37_asn1_time.t ................. ok     
t/local/38_priv-key.t .................. ok     
t/local/39_pkcs12.t .................... ok     
t/local/40_npn_support.t ............... ok   
t/local/41_alpn_support.t .............. ok   
t/local/42_info_callback.t ............. ok   
t/local/43_misc_functions.t ............ ok     
t/local/44_sess.t ...................... ok     
t/local/45_exporter.t .................. ok     
t/local/50_digest.t .................... ok       
t/local/61_threads-cb-crash.t .......... skipped: your perl is not compiled with ithreads
t/local/62_threads-ctx_new-deadlock.t .. skipped: your perl is not compiled with ithreads
t/local/63_ec_key_generate_key.t ....... ok   
t/local/64_ticket_sharing.t ............ ok     
t/local/65_security_level.t ............ ok     
t/local/65_ticket_sharing_2.t .......... ok   
t/local/66_curves.t .................... ok   
t/local/kwalitee.t ..................... skipped: these tests are for only for release candidate testing. Enable with RELEASE_TESTING=1

Test Summary Report
-------------------
t/local/10_rand.t                    (Wstat: 256 Tests: 52 Failed: 1)
  Failed test:  3
  Non-zero exit status: 1
Files=40, Tests=3039,  6 wallclock secs ( 0.40 usr  0.05 sys +  4.44 cusr  0.31 csys =  5.20 CPU)
Result: FAIL
Failed 1/40 test programs. 1/3039 subtests failed.
make: *** [Makefile:1081: test_dynamic] Ошибка 255
FAIL
```

**Comment by chrisnovakovic** [comment]
I don't think this is one we've seen before - does your environment define a value for `RANDFILE` and/or `HOME`? Is the file at `~/.rnd` writable?

**Comment by mche** [comment]
```
$ env | grep HOME
HOME=/home/mche
```
```
$ ls -l ~/.rnd 
-rw------- 1 mche mche 1024 oct 16  2018 /home/mche/.rnd
```

But with perl-5.28.2 successfully installed Net-SSLeay-1.88

**Comment by h-vn** [comment]
I'd like to leave this open to encourage possible other reports should this happen again. When I added the test I had the idea to make sure the call does not break completely in a future library release. It's surprising and to see single failures like this and it would be good to hear if they happen again.

**Comment by mche** [comment]
Hi again,

So trouble does repeat again [log](https://gist.github.com/mche/86a48b307c18c1f7aa47e454ee5e471d)

**Comment by chrisnovakovic** [comment]
Thanks for the update, Mikhail!

@h-vn has looked into this and was able to reproduce the bug by unsetting `HOME` before the test runs. We suspect it might be because your Perl 5.26.1 cpanm build environment doesn't define `HOME` for some reason. Could you try adding the following after line 15 in `t/local/10_rand.t` and running the test again?

```perl
$ENV{HOME} = "/tmp";
```

**Comment by mche** [comment]
@chrisnovakovic, I had try your line but none success with same error: _Failed test 'RAND_file_name returns defined value'_.

And also `warn map "$_: $ENV{$_}\n", keys %ENV;` at 10_rand.t did look me **HOME: /home/mche**

```
$ ls -l ~/.rnd 
-rw------- 1 mche mche 1024 oct 16  2018 /home/mche/.rnd
```

**Comment by chrisnovakovic** [comment]
Could you try the same for `RANDFILE`? [Those are the only two environment variables whose values are looked up by `RAND_file_name` on Linux](https://github.com/openssl/openssl/blob/256d41d4371720ccfe1a4fead6bd28ed5071bcdd/crypto/rand/randfile.c#L249), so if that doesn't work, I'm not sure what to suggest...

**Comment by mche** [comment]
`RANDFILE=/home/mche/.rnd make test`

But none success

**Comment by h-vn** [comment]
There's something I noticed in the [log](https://gist.github.com/mche/86a48b307c18c1f7aa47e454ee5e471d) you linked to 4 days ago: the home directory appears to be for user `guest`. For example (snippets from parts of log: lines [2](https://gist.github.com/mche/86a48b307c18c1f7aa47e454ee5e471d#file-gistfile1-txt-L2) and [328](https://gist.github.com/mche/86a48b307c18c1f7aa47e454ee5e471d#file-gistfile1-txt-L328)):

```
Work directory is /home/guest/.cpanm/work/1611825812.23203
...
# Perl information:
#   Version:         '5.026001'
#   Executable path: '/home/guest/perl5/perlbrew/perls/perl-5.26.1/bin/perl'
# 
# libssl information:
#   SSLEAY_VERSION:      'OpenSSL 1.1.1i  8 Dec 2020'
#   SSLEAY_CFLAGS:       'compiler: x86_64-pc-linux-gnu-gcc -fPIC -pthread -m64 -Wa,--noexecstack -O2 -march=x86-64 -pipe -fno-strict-aliasing -Wa,--noexecstack -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DZLIB -DNDEBUG  -DOPENSSL_NO_BUF_FREELISTS'
#   SSLEAY_BUILT_ON:     'built on: Fri Dec 11 05:42:52 2020 UTC'
#   SSLEAY_PLATFORM:     'platform: linux-x86_64'
#   SSLEAY_DIR:          'OPENSSLDIR: "/etc/ssl"'
#   OPENSSL_ENGINES_DIR: 'ENGINESDIR: "/usr/lib64/engines-1.1"'
```

Could it be that the built is done in such a way that it runs as user `guest` who doesn't have environment that has `HOME` set? As an additional point, Perl 5.26 is much older than OpenSSL 1.1.1i, so the build environment doesn't seem to be something that comes with any Linux distribution.

**Comment by mche** [comment]
That is right **guest** user  make tests, dont worry.

At moment I did `cpanm  --force  Net::SSLeay`  install and it does work. I will watching.

Lot of thanks.

**Comment by kberry** [comment]
With Perl 5.34.0 and Net:SSLeay 1.90, if envvar HOME is not set, make test (reproducibly) fails for me per the original report here. Presence or absence of RANDFILE does not matter. x86_64-linux, CentOS 7, though I doubt that matters.

**Comment by h-vn** [comment]
There's one thing that's not clear to me: was there some type of setuid environment used when running the tests? OpenSSL 1.1.1d uses its internal function `ossl_safe_getenv()` which may, by one way or other, return `NULL` instead of the requested variable value.

In any case, I've updated the use of `HOME` and `RANDFILE` environment variables in tests and enhanced documentation and compatibility with OpenSSL 1.1.0 series. Please see the related #342 for the details.

**Comment by h-vn** [comment]
If there are still failures with `10_rand.t`, please report them and tell if setuid, or otherwise restricted, environment was used to run the tests.

**Comment by kberry** [comment]
In my case at least, no setuid or root environment involved. I had
cleared the environment (env -i) for installation because of a painful
bug in libwww (https://github.com/libwww-perl/libwww-perl/issues/372)
which caused reports of "conflicts" (that weren't conflicts) about
dozens of envvars set in my personal environment, which made everything
far too noisy to be bearable. This turned up the unexpected requirement
of $HOME for the ssleay tests.

Thanks for working on it, I look forward to trying the fix. --karl
