### ISSUE TITLE
Script got crashed when using CTX_set_next_proto_select_cb

### ISSUE THREAD

**Issue by dylc5190** [radiator-software/p5-net-ssleay#222]
I reported an issue in openssl https://github.com/openssl/openssl/issues/13521 regarding using NPN callback with this syntax

`Net::SSleay::CTX_set_next_proto_select_cb($ctx, $arrayref);`

Meanwhile I'm thinking how to avoid the crash with existing openssl.  Adding two lines after line 1191 avoid the crash.
https://github.com/radiator-software/p5-net-ssleay/blob/8c9187507af9039e3bf68e74ca04cd20f95591fd/SSLeay.xs#L1191
```
tmpsv = newSVpv((const char*)*out, *outlen);
*out = (unsigned char *)SvPVX(tmpsv);
```
Is this an acceptable solution?

**Comment by chrisnovakovic** [comment]
Looks good to us - patch submitted as PR #222, crediting you in `Changes`. Thanks!
