### ISSUE TITLE
Intall fails on M1 macos using brew openssl

### ISSUE THREAD

**Issue by haroldfrayman** [radiator-software/p5-net-ssleay#268]
The find_openssl_prefix guesses in Makefile.PL do not include '/opt/homebrew/opt/openssl' => '/opt/homebrew/opt/openssl', (which worked for me) and fails without it.

**Comment by roryzweistra** [comment]
I have relatable issues but setting the openssl prefix doesn't solve my case.

`Configuring Net-SSLeay-1.90
Running Makefile.PL
Do you want to run external tests?
These tests *will* *fail* if you do not have network connectivity. [n] n
*** Found LibreSSL-2.8.3 installed in /usr
*** Be sure to use the same compiler and options to compile your OpenSSL, perl,
    and Net::SSLeay. Mixing and matching compilers is not supported.
Checking if your kit is complete...
Looks good
WARNING: /opt/homebrew/Cellar/perl/5.32.1_1/bin/perl is loading libcrypto in an unsafe way
-> N/A
`

I've tried this with system perl, brew perl and multiple perlbrew perls.
Google came up with a temp solution to build homebrew using  x86_64 architecture.
This did work for the libcrypto error, but gave me a whole different set of issues.

Any ideas what the real solution is?

**Comment by hakonhagland** [comment]
> perl is loading libcrypto in an unsafe way 

I reproduced the behavior for a simple C program [here](https://stackoverflow.com/q/67025761/2173773). Is this a bug in `libssl.dylib` or am I calling `dlopen()` in the wrong way?

**Comment by kyzn** [comment]
A hacky way around this that I came across GitHub.

I have perl 5.32.1 installed via perlbrew, cpanm installed via perlbrew and openssl@1.1 installed via brew.

```bash
kivanc@mac:~$ which perl
/Users/kivanc/perl5/perlbrew/perls/perl-5.32.1/bin/perl
kivanc@mac:~$ which cpanm
/Users/kivanc/perl5/perlbrew/bin/cpanm
kivanc@mac:~$ which openssl
/opt/homebrew/opt/openssl@1.1/bin/openssl
```

With this, plain `cpanm Net::SSLeay` fails with this message:
```text
 *** Found LibreSSL-2.8.3 installed in /usr
 *** Be sure to use the same compiler and options to compile your OpenSSL, perl,
     and Net::SSLeay. Mixing and matching compilers is not supported.
```
and I believe this is because of [guesses](https://github.com/radiator-software/p5-net-ssleay/blob/master/Makefile.PL#L308-L326) do not include my `/opt/homebrew/opt/openssl@1.1`. No worries, I can define `OPENSSL_PREFIX` manually to point to my openssl: `OPENSSL_PREFIX=/opt/homebrew/opt/openssl@1.1 cpanm Net::SSLeay`

Now this fails with the error:
```text
 WARNING: /Users/kivanc/perl5/perlbrew/perls/perl-5.32.1/bin/perl is loading libcrypto in an unsafe way
 -> N/A
 -> FAIL Configure failed for Net-SSLeay-1.90. See /Users/kivanc/.cpanm/work/<some numbers here>/build.log for details.
```

Progress, but not quite there. [Here's](https://github.com/sergot/openssl/issues/81#issuecomment-782916961) the hack:

```bash
sudo ln -s /opt/homebrew/opt/openssl@1.1/lib/libssl.1.1.dylib /usr/local/lib/libssl.dylib
sudo ln -s /opt/homebrew/opt/openssl@1.1/lib/libcrypto.1.1.dylib /usr/local/lib/libcrypto.dylib
OPENSSL_PREFIX=/opt/homebrew/opt/openssl@1.1 cpanm Net::SSLeay
```
Adjust to your `which openssl` of course. If you are trying to install Net::SSLeay via `carton install` for example, you can prepend that `OPENSSL_PREFIX=...` to `carton install` to make it work too.

**Comment by chrisnovakovic** [comment]
Fixed in #292 - this will be part of Net-SSLeay 1.92. Thanks for the report!

**Comment by theory** [comment]
```
$ echo $OPENSSL_PREFIX
/opt/homebrew/opt/openssl

$ curl -s https://patch-diff.githubusercontent.com/raw/radiator-software/p5-net-ssleay/pull/292.diff | patch -p1
patching file Makefile.PL
Hunk #1 succeeded at 251 (offset -55 lines).

$ perl Makefile.PL 
Do you want to run external tests?
These tests *will* *fail* if you do not have network connectivity. [n] 
*** Found OpenSSL-3.0.0 installed in /opt/homebrew/opt/openssl
*** Be sure to use the same compiler and options to compile your OpenSSL, perl,
    and Net::SSLeay. Mixing and matching compilers is not supported.
Checking if your kit is complete...
Looks good
WARNING: /Users/david/.plenv/versions/5.34.0/bin/perl is loading libcrypto in an unsafe way
[1]    17617 abort      perl Makefile.PL

$ sudo ln -s $OPENSSL_PREFIX/lib/libssl.dylib /usr/local/lib/
$ sudo ln -s $OPENSSL_PREFIX/lib/libcrypto.dylib /usr/local/lib/
$ perl Makefile.PL 
Do you want to run external tests?
These tests *will* *fail* if you do not have network connectivity. [n] 
*** Found OpenSSL-3.0.0 installed in /opt/homebrew/opt/openssl
*** Be sure to use the same compiler and options to compile your OpenSSL, perl,
    and Net::SSLeay. Mixing and matching compilers is not supported.
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Net::SSLeay
Writing MYMETA.yml and MYMETA.json
```

I haver to admit that I don't understand why the symlinks are necessary.

**Comment by adamtaylor** [comment]
@kyzn comment (hack) worked for me 🙌. Would be great to see this fix released. Is there anything any of us can do to help? I'd be happy to help in some way.
