### ISSUE TITLE
Failing test PEM_get_string_PrivateKey+passwd for openssl 3.0.0

### ISSUE THREAD

**Issue by michal-josef-spacek** [radiator-software/p5-net-ssleay#272]
This test (t/local/33_x509_create_cert.t) is failing from openssl 3.0.0- alpha1 to alpha17 on Fedora 33
```
not ok 37 - PEM_get_string_PrivateKey+passwd
#   Failed test 'PEM_get_string_PrivateKey+passwd'`
#   at t/local/33_x509_create_cert.t line 98.
#                   undef
#     doesn't match '(?^:-----BEGIN (ENCRYPTED|RSA) PRIVATE KEY-----)'
```

Example to test:
```
#!/usr/bin/env perl

use strict;
use warnings;

use Data::Printer;
use Net::SSLeay;

my $pk = Net::SSLeay::EVP_PKEY_new();
my $rsa = Net::SSLeay::RSA_generate_key(2048, &Net::SSLeay::RSA_F4);
Net::SSLeay::EVP_PKEY_assign_RSA($pk, $rsa);
my $key_pem1 = Net::SSLeay::PEM_get_string_PrivateKey($pk);
my $key_pem2 = Net::SSLeay::PEM_get_string_PrivateKey($pk, 'password');

p $pk;
p $key_pem1;
p $key_pem2;
```

Issue is with default cipher which is DES-CBC, which is insecure and not working in this configuration (Fedora 33, crypto-policies with DES-CBC disabled)
I am proposing change default cipher to DES-EDE. Test is testing default cipher. Test for explicit cipher DES-EDE3-CBC is working.

**Comment by michal-josef-spacek** [comment]
https://github.com/radiator-software/p5-net-ssleay/pull/273

**Comment by h-vn** [comment]
I think there are two options we could consider:

1. Load the legacy provider in the test file or when `PEM_get_stringPrivateKey` is called. This is with 3.0.0 and later.
2. Switch the default algorithm from `EVP_des_cbc()` to `EVP_des_ede3_cbc()`

With legacy provider, the functionality of `PEM_get_string_PrivateKey()` doesn't change.

Three key triple DES in CBC mode seems to be one of the algorithms in [PCKS#5 2.0](https://datatracker.ietf.org/doc/html/rfc2898). Based on my tests, it seems to work with multiple OpenSSL versions, including 3.0.0 beta2 and its default provider.

Note that your patch uses `EVP_des_ede()` which is two key triple DES in ECB mode. I think this is why it was triggering failures during tests. `Net::SSLeay::OpenSSL_add_all_algorithms()` would fix this, but I'd say ECB mode is not desired.

**Comment by h-vn** [comment]
Thanks Paul. I just linked issue #293 to this one. The current plan is to not immediately change the algorithm from `EVP_dec_cb()` but load OpenSSL 3.0 legacy provider instead. This allows `PEM_get_stringPrivateKey()` to continue working as it does now. The default encryption algorithm can be changed later to something that does not require legacy provider, such as AES or 3DES.

While the legacy provider allows the tests to pass, there's still the problem that it won't help existing code. On the other hand, changing the default encryption algorithm breaks backwards compatibility.

In any case, I'd say we need to support provider loading now, so I'll do this as the next step.

**Comment by michal-josef-spacek** [comment]
@h-vn yes, changing of default encryption algorithm breaks backwards compatibility. That's fact and this will be in future again and again. And situation will be worst, because legacy support will go out, I believe. This is not good situation, still i don't know how to prevent this situation. Maybe some configuration and check for algorithm presence.

That's funny. Acually i have DES_EDE in RHEL 9, so i need to change to Paul version from Fedora or change to other :-)
