### ISSUE TITLE
Add SSL_CTX_set_security_level and related functions

### ISSUE THREAD

**Issue by h-vn** [radiator-software/p5-net-ssleay#37]
OpenSSL 1.1.0 added SSL_CTX_set_security_level to control various parameters. Applications may want to control the security level to allow compatibility with older OpenSSL versions or increase the security level from the default.

**Comment by chrisnovakovic** [comment]
[RT#126986](https://rt.cpan.org/Ticket/Display.html?id=126986) might do everything we need here, courtesy of Damyan Ivanov.

**Comment by h-vn** [comment]
Also closes https://rt.cpan.org/Ticket/Display.html?id=126986
