### ISSUE TITLE
Huge numbers of compound-token-split-by-macro warnings when building with Clang >= 12

### ISSUE THREAD

**Issue by chrisnovakovic** [radiator-software/p5-net-ssleay#383]
Compiling `SSLeay.xs` with Clang >= 12 results in 4,234 `compound-token-split-by-macro` compiler warnings.

Some are caused by `ppport.h`, which was [fixed in version 3.64 of Devel::PPPort](https://github.com/Dual-Life/Devel-PPPort/commit/e124e16191f3c971c6efad3f9def300e2ee57ef8):

```
SSLeay.xs:1935:5: warning: '}' and ')' tokens terminating statement expression appear in different macro expansion contexts [-Wcompound-token-split-by-macro]
    MUTEX_INIT(&LIB_init_mutex);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/perl/5.34.0/lib/perl5/5.34.0/darwin-thread-multi-2level/CORE/thread.h:198:5: note: expanded from macro 'MUTEX_INIT'
    } STMT_END
    ^
SSLeay.xs:1935:5: note: ')' token is here
    MUTEX_INIT(&LIB_init_mutex);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/perl/5.34.0/lib/perl5/5.34.0/darwin-thread-multi-2level/CORE/thread.h:198:7: note: expanded from macro 'MUTEX_INIT'
    } STMT_END
      ^~~~~~~~
./ppport.h:3827:20: note: expanded from macro 'STMT_END'
#  define STMT_END      )
                        ^
```

Others are caused by `perl.h`, which has been [fixed in Perl](https://www.nntp.perl.org/group/perl.perl5.porters/2022/03/msg263187.html) but is apparently hard to backport to earlier branches (and we support Perl versions already in circulation that will forever be affected by this anyway):

```
In file included from SSLeay.xs:145:
In file included from /usr/local/Cellar/perl/5.34.0/lib/perl5/5.34.0/darwin-thread-multi-2level/CORE/perl.h:7109:
/usr/local/Cellar/perl/5.34.0/lib/perl5/5.34.0/darwin-thread-multi-2level/CORE/inline.h:2821:5: warning: '(' and '{' tokens introducing statement expression appear in different macro expansion contexts [-Wcompound-token-split-by-macro]
    GETENV_UNLOCK;
    ^~~~~~~~~~~~~
/usr/local/Cellar/perl/5.34.0/lib/perl5/5.34.0/darwin-thread-multi-2level/CORE/perl.h:7076:28: note: expanded from macro 'GETENV_UNLOCK'
#    define GETENV_UNLOCK  ENV_READ_UNLOCK
                           ^~~~~~~~~~~~~~~
/usr/local/Cellar/perl/5.34.0/lib/perl5/5.34.0/darwin-thread-multi-2level/CORE/perl.h:7065:31: note: expanded from macro 'ENV_READ_UNLOCK'
#  define ENV_READ_UNLOCK     PERL_READ_UNLOCK(&PL_env_mutex)
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/perl/5.34.0/lib/perl5/5.34.0/darwin-thread-multi-2level/CORE/thread.h:305:9: note: expanded from macro 'PERL_READ_UNLOCK'
        MUTEX_UNLOCK(&(mutex)->lock);                               \
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/perl/5.34.0/lib/perl5/5.34.0/darwin-thread-multi-2level/CORE/thread.h:218:5: note: expanded from macro 'MUTEX_UNLOCK'
    STMT_START {                                                \
    ^~~~~~~~~~
/usr/local/Cellar/perl/5.34.0/lib/perl5/5.34.0/darwin-thread-multi-2level/CORE/perl.h:737:29: note: expanded from macro 'STMT_START'
#   define STMT_START   (void)( /* gcc supports "({ STATEMENTS; })" */
                              ^
/usr/local/Cellar/perl/5.34.0/lib/perl5/5.34.0/darwin-thread-multi-2level/CORE/inline.h:2821:5: note: '{' token is here
    GETENV_UNLOCK;
    ^~~~~~~~~~~~~
/usr/local/Cellar/perl/5.34.0/lib/perl5/5.34.0/darwin-thread-multi-2level/CORE/perl.h:7076:28: note: expanded from macro 'GETENV_UNLOCK'
#    define GETENV_UNLOCK  ENV_READ_UNLOCK
                           ^~~~~~~~~~~~~~~
/usr/local/Cellar/perl/5.34.0/lib/perl5/5.34.0/darwin-thread-multi-2level/CORE/perl.h:7065:31: note: expanded from macro 'ENV_READ_UNLOCK'
#  define ENV_READ_UNLOCK     PERL_READ_UNLOCK(&PL_env_mutex)
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/perl/5.34.0/lib/perl5/5.34.0/darwin-thread-multi-2level/CORE/thread.h:305:9: note: expanded from macro 'PERL_READ_UNLOCK'
        MUTEX_UNLOCK(&(mutex)->lock);                               \
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/perl/5.34.0/lib/perl5/5.34.0/darwin-thread-multi-2level/CORE/thread.h:218:16: note: expanded from macro 'MUTEX_UNLOCK'
    STMT_START {                                                \
               ^
```

This isn't a bug per se, but it makes debugging CPAN smoke tester reports from recent macOS versions impossible because all this noise makes it too hard to spot any meaningful warnings or errors, and the output is truncated after the first 1MB anyway - e.g. from Net-SSLeay 1.92:

https://www.cpantesters.org/cpan/report/a2b6b16c-8b2d-11ec-b97a-f8e101776541
https://www.cpantesters.org/cpan/report/dedbe1ba-8b2a-11ec-9457-146e02776541
https://www.cpantesters.org/cpan/report/c6708084-8b27-11ec-a7cc-42cf02776541
https://www.cpantesters.org/cpan/report/74b460b4-a943-11ec-80ac-91972641c30e

**Comment by chrisnovakovic** [comment]
#384 removes 4,129 of these warnings. There's not much we can do about the rest - we'll have to silence them when building with Clang >= 12.

**Comment by chrisnovakovic** [comment]
The relevant commit that fixes this in blead is https://github.com/Perl/perl5/commit/415da10787d8fa5176e711559172aa0604ec3d0d, which is part of Perl 5.35.2. It might be that we want to limit suppression of this warning to earlier Perl versions if we think it has any value (although the jury's still out in that regard).

**Comment by chrisnovakovic** [comment]
#385 silences the remainder of these warnings.

**Comment by h-vn** [comment]
One option to limit this could be to modify CCFLAGS in Makefile.PL. There is done to set `-DNET_SSLEAY_32BIT_INT_PERL`,  see #315, and maybe we could also use it to `-D` a flag that enables the pragma for the older Perls.

**Comment by h-vn** [comment]
Just noticed that macOS Catalina 10.15.7 and compiler that comes with its Xtools triggers this warning:
```
SSLeay.xs:141:34: warning: unknown warning group '-Wcompound-token-split-by-macro', ignored [-Wunknown-warning-option]
#pragma clang diagnostic ignored "-Wcompound-token-split-by-macro"
                                 ^
```
The compiler claims to be clang 12.0.0, but it seems not to implement the option but on the other hand, it doesn't trigger warnings that stock clang 12 does. In short: something to note but I don't think there's need to address it separately.

Also see commet in PR #390

**Comment by chrisnovakovic** [comment]
#390 has been merged into master - this ensures that `-Wcompound-token-split-by-macro` is only enabled for Perl < 5.35.2, and that the pragma doesn't itself trigger warnings with versions of Clang that appear to be affected but actually aren't.
