### ISSUE TITLE
Build failed because of -Werror=declaration-after-statement

### ISSUE THREAD

**Issue by dharanlinux** [radiator-software/p5-net-ssleay#407]
Hi Team,

    Facing the below build issue because of -Werror=declaration-after-statement added in the CCFLAGS.

Error log:

```
SSLeay.xs: In function 'XS_Net__SSLeay_RSA_generate_key':
SSLeay.xs:6219:8: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
        int rc;
        ^
SSLeay.xs:6235:8: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
        BN_GENCB *new_cb;
        ^
```

**Comment by h-vn** [comment]
Thanks for the report. What platform you are using (Linux, BSD, something else?) and what the compiler (gcc?) is? If I do something like this I get almost similar error:
```
% OPENSSL_PREFIX=$HOME/opt/openssl-1.1.1q perl Makefile.PL CC=/usr/local/Cellar/gcc/12.2.0/bin/gcc-12 CCFLAGS=-Werror=declaration-after-statement
% make
[cut]
SSLeay.xs: In function 'XS_Net__SSLeay_RSA_generate_key':
SSLeay.xs:6331:8: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
 6331 |        int rc;
      |        ^~~
SSLeay.xs:6347:8: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
 6347 |        BN_GENCB *new_cb;
      |        ^~~~~~~~
```

However, as you can see, I needed to add the compiler flag manually. I'd be interested to know if there's a platform that uses this by default.

**Comment by dharanlinux** [comment]
I am using the linux and the compiler is gcc-5.5.0. The '-Werror=declaration-after-statement' flag is appending from perl source. 
Yes this flag is used by my platform by default.

**Comment by dharanlinux** [comment]
Can I get the fix to build the source with  -Werror=declaration-after-statement flag.

**Comment by chrisnovakovic** [comment]
Thanks for the report. This does indeed seem to be a bug in the way that variables are declared in `RSA_generate_key` - the default values of `perl_cb` and `perl_data` cause code to be emitted before the variable declarations your error message identifies. In #410 I've refactored the declarations of the variables in this function so that they happen before the default-setting code is emitted, which makes it compile under `-Werror=declaration-after-statement`.
