### ISSUE TITLE
Install fails for Net-SSLeay-1.92 on new MacBook Pro M2 (ARM)

### ISSUE THREAD

**Issue by daynez** [radiator-software/p5-net-ssleay#426]
Building out a new MacBook Pro M2 and installing Perl and modules.
Net-SSLeay-1.92.tar has compile issues on the "make test" step.  I copied the tarball up to an Intel iMac and the entire process completed fine.  I'm pretty sure the issue is in the latest compiler that ships with the Macs.

The captured output from stderr is included in the attached file 'notes.txt'
Full output from 'perl -V' is in the attached file 'perl-V.txt'

Please let me know if there is anything else I can supply for you.

Thanks,
Dayne Zimmerman
daynez@mindspring.com

Running MacOS 13.2 on M2 processor.
$ openssl version
LibreSSL 3.7.0
[notes.txt](https://github.com/radiator-software/p5-net-ssleay/files/10717149/notes.txt)
[perl-V.txt](https://github.com/radiator-software/p5-net-ssleay/files/10717151/perl-V.txt)

**Comment by h-vn** [comment]
Release 1.94 is now out. It incorporates all the fixes in 1.93_n developer relases and should fix the warnings triggered by `-Wcompound-token-split-by-macro`. I'm closing this issue now, but if anything comes up, please don't hesitate to create a new issue.
