### ISSUE TITLE
Wrong linker options used when ExtUtils::PkgConfig is installed

### ISSUE THREAD

**Issue by chrisnovakovic** [radiator-software/p5-net-ssleay#465]
When Net-SSLeay is built against a copy of OpenSSL with compression enabled (obviously you shouldn't do this now, but we still support versions of OpenSSL that enable it by default), pointing to that copy of OpenSSL with `OPENSSL_PREFIX` causes a linking failure when ExtUtils::PkgConfig is also installed. Digging into it, it seems that this happens because the compiler and linker options are unconditionally supplied by pkg-config whenever ExtUtils::PkgConfig is installed; because pkg-config points to the system-wide copy of OpenSSL by default, and because most OSes now ship an OpenSSL without compression enabled, the `-lz` linker option is missing. This is just one case in which `Makefile.PL` does the wrong thing in this regard, but I can think of other scenarios where it'll get it wrong too.

We've run out of time to fix and comprehensively test this before 1.94, but pkg-config support will be enormously useful when it makes it into a stable release, and we'll bring it back in time for 1.96.

**Comment by h-vn** [comment]
OpenSSL 3.2 adds support for [certificate compression](https://www.openssl.org/docs/manmaster/man3/COMP_zlib.html). The supported compression methods are zlib, Zstandard (zstd) and Brotli. Here's what `ldd` shows when all these are enabled with OpenSSL compiled from the master branch. It might be that there are even more libraries that `Net::SSleay` compile needs:
```
 % ldd ~/opt/openssl-master/lib64/libcrypto.so.3
	linux-vdso.so.1 (0x00007fffff3bc000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fb4df062000)
	libbrotlienc.so.1 => /lib/x86_64-linux-gnu/libbrotlienc.so.1 (0x00007fb4defd1000)
	libbrotlidec.so.1 => /lib/x86_64-linux-gnu/libbrotlidec.so.1 (0x00007fb4defc3000)
	libzstd.so.1 => /lib/x86_64-linux-gnu/libzstd.so.1 (0x00007fb4deef4000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb4deccc000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb4debe3000)
	libbrotlicommon.so.1 => /lib/x86_64-linux-gnu/libbrotlicommon.so.1 (0x00007fb4debc0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb4df5ef000)
```
