### ISSUE TITLE
`openssl30` doesn't exist in FreeBSD Ports any more

### ISSUE THREAD

**Issue by chrisnovakovic** [radiator-software/p5-net-ssleay#477]
This is causing CI failures like [this](https://github.com/radiator-software/p5-net-ssleay/actions/runs/8547572807/job/23419969075?pr=476):

```
Pseudo-terminal will not be allocated because stdin is not a terminal.
Updating FreeBSD repository catalogue...
Fetching packagesite.pkg: .......... done
Processing entries: .......... done
FreeBSD repository update completed. 33638 packages processed.
All repositories are up to date.
pkg: No packages available to install matching 'openssl30' have been found in the repositories
```

[`openssl32`](https://ports.freebsd.org/cgi/ports.cgi?query=openssl32&stype=all&sektion=all) is present, so we should probably switch to that.

**Comment by AmanAraikar2004** [comment]
Hey Chris, I know it's not a correct way to connect with you. I read this article (https://www.kernel.org/doc/html/latest/admin-guide/nfs/nfsroot.html) and saw you made the last modification in it. I'm a college student and don't have a deep knowledge about all the concepts but I want to learn it and do this. Can you help me in that ? Also I know it's not the correct place to chat so here is my mail id (aaaaaraikar@proton.me) and if you have twitter (https://x.com/AmanAraikar).
