### ISSUE TITLE
Travis: test against Perl 5.28

### ISSUE THREAD

**Issue by chrisnovakovic** [radiator-software/p5-net-ssleay#49]
AppVeyor is currently configured to build and test Net-SSLeay against Perl 5.28.0, but Travis isn't. When [Travis makes the 5.28 branch available](https://github.com/travis-ci/travis-ci/issues/9792), the Travis configuration should be updated to suit.

**Comment by h-vn** [comment]
While working on #50 noticed that Perl 5.28 seems to be available.
